[slideshow]
interval = "30s"    # time between slides (e.g. "30s", "1m", "2m30s")
thumb_width = 80    # thumbnail width in pixels for keyboard navigation

[schedule]
reload_time = "01:00"  # reload this file daily at this time (HH:MM)

[schedule.monday]
all = [ "08:00-12:00", "13:30-22:00" ]

[schedule.tuesday]
all = [ "08:00-12:00", "13:30-22:00" ]

[schedule.wednesday]
all = [ "08:00-12:00", "13:30-22:00" ]

[schedule.thursday]
all = [ "08:00-12:00", "13:30-22:00" ]
second = [ "07:00-08:00" ]

[schedule.friday]
all = [ "08:00-12:00", "13:30-22:00" ]

[schedule.saturday]
all = [ "10:00-18:00" ]
last = [ "18:00-22:00"]

# sunday: off all day (no section needed)
